version: '3'

services:
  laravel-app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/user/share/nginx
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: 
    driver: local